name: mixology_backend
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.3.0
  dart_jsonwebtoken: ^2.7.1
  dotenv: ^4.0.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^1.2.2
  meta: ^1.0.0
  mutex: ^3.0.1
  postgres: ^2.0.0
  sane_uuid: ^1.0.0-alpha.4
  shelf: ^1.4.0
  shelf_plus: ^1.5.1
  shelf_router: ^1.1.0
  spotify_api: ^0.3.0-alpha

dev_dependencies:
  build_runner: ^2.3.3
  http: ^0.13.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lints: ^2.0.0
  # shelf_router_generator: ^1.0.5
  test: ^1.21.0
