---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  secretStoreRef:
    name: doppler-born
    kind: ClusterSecretStore
  target:
    name: api-secrets
  dataFrom:
    - find:
        path: "MIXOLOGY_API_"
      rewrite:
        - regexp:
            source: "MIXOLOGY_API_(.+)"
            target: "$1"
