apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
stringData:
  CLIENT_SECRET: ${{ .Values.spotify.clientSecret }}
  OAUTH_JWT_KEY: ${{ .Values.jwt.oauth }}
  ACCESS_JWT_KEY: ${{ .Values.jwt.access }}
  REFRESH_JWT_KEY: ${{ .Values.jwt.refresh }}
