apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
stringData:
  CLIENT_SECRET: {{ .Values.spotify.clientSecret | quote }}
  OAUTH_JWT_KEY: {{ .Values.jwt.oauth | quote }}
  ACCESS_JWT_KEY: {{ .Values.jwt.access | quote }}
  REFRESH_JWT_KEY: {{ .Values.jwt.refresh | quote }}
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
