name: Main

on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Dart format check
        run: dart format --set-exit-if-changed --output=none lib test bin

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Get dependencies
        run: dart pub get
      - name: Code generation
        run: dart run build_runner build
      - name: Dart analyze
        run: dart analyze --fatal-infos

  build-app-image:
    needs:
      - check-format
      - lint
    uses: BjoernPetersen/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: ubicloud-standard-2-arm
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}
      image-name: "mixology-api/app"

  build-migrations-image:
    needs:
      - check-format
      - lint
    uses: BjoernPetersen/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      context: "./migrations"
      runner-name-build: ubicloud-standard-2-arm
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}
      image-name: "mixology-api/migrations"

  deploy:
    runs-on: ubuntu-latest
    concurrency: production
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-app-image
      - build-migrations-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v4
    strategy:
      matrix:
        image-part: [ app, migrations ]
    with:
      image-name: mixology-api/${{ matrix.image-part }}
